pool:
  vmImage: 'ubuntu-16.04'
variables: # pipeline-level
  PIPENV_VENV_IN_PROJECT: 'true'
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'
  - step:
      name: install dependencies and building djangodemo 
      script:

        - sudo python -m pip install --upgrade pip 
        - sudo pip install --upgrade pip
        - sudo pip install pipenv
        - sudo pipenv install
        - sudo pipenv install Django==2.2
        - sudo pipenv install pytest-django
      

        - [ $EUID == 0 ] && SUDO=" || SUDO=sudo && $SUDO chown -R circleci:circleci /usr/local/bin
        - [ $EUID == 0 ] && SUDO=" || SUDO=sudo && $SUDO chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
        - sudo pipenv run pytest --junitxml=test-results/junit.xml djangodemo/tests
        - sudo python djangodemo/setup.py sdist
